wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725545421
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      - 103
      3:
      - 7
      - 16
      - 23
      - 24
      - 66
      4: 3.9.19
      5: 0.17.8
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
data:
  desc: null
  value:
    ch1_fname: ER/GT_all.mrc
    ch2_fname: CCPs/GT_all.mrc
    data_type: 2
    image_size: 256
    num_channels: 2
    sampler_type: 0
datadir:
  desc: null
  value: ''
exptname:
  desc: null
  value: ''
git:
  desc: null
  value:
    branch: ''
    changedFiles: []
    latest_commit: ''
    untracked_files: []
hostname:
  desc: null
  value: ''
loss:
  desc: null
  value:
    loss_type: 9
model:
  desc: null
  value:
    decoder:
      conv2d_bias: true
    encoder: {}
    img_shape:
    - 256
    - 256
    in_chans: 1
    model_type: 29
    upscale: 1
    use_vampprior: false
training:
  desc: null
  value:
    batch_size: 4
    earlystop_patience: 10
    grad_clip_norm_value: 0.5
    gradient_clip_algorithm: value
    lr: 0.001
    num_epochs: 400
    pre_trained_ckpt_fpath: ''
    precision: 32
workdir:
  desc: null
  value: /FILL_IN_THE_WORKDIR
